/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComoPensaRouteImport } from './routes/como-pensa'
import { Route as DecidirRouteImport } from './routes/decidir'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as MeuMapaRouteImport } from './routes/meu-mapa'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthMigrateRouteImport } from './routes/auth/migrate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoPensaRoute = ComoPensaRouteImport.update({
  id: '/como-pensa',
  path: '/como-pensa',
  getParentRoute: () => rootRouteImport,
} as any)
const DecidirRoute = DecidirRouteImport.update({
  id: '/decidir',
  path: '/decidir',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuMapaRoute = MeuMapaRouteImport.update({
  id: '/meu-mapa',
  path: '/meu-mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMigrateRoute = AuthMigrateRouteImport.update({
  id: '/auth/migrate',
  path: '/auth/migrate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-pensa': typeof ComoPensaRoute
  '/decidir': typeof DecidirRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/meu-mapa': typeof MeuMapaRoute
  '/perfil': typeof PerfilRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/migrate': typeof AuthMigrateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-pensa': typeof ComoPensaRoute
  '/decidir': typeof DecidirRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/meu-mapa': typeof MeuMapaRoute
  '/perfil': typeof PerfilRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/migrate': typeof AuthMigrateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-pensa': typeof ComoPensaRoute
  '/decidir': typeof DecidirRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/meu-mapa': typeof MeuMapaRoute
  '/perfil': typeof PerfilRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/migrate': typeof AuthMigrateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-pensa'
    | '/decidir'
    | '/historico'
    | '/login'
    | '/mapa'
    | '/meu-mapa'
    | '/perfil'
    | '/auth/callback'
    | '/auth/migrate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-pensa'
    | '/decidir'
    | '/historico'
    | '/login'
    | '/mapa'
    | '/meu-mapa'
    | '/perfil'
    | '/auth/callback'
    | '/auth/migrate'
  id:
    | '__root__'
    | '/'
    | '/como-pensa'
    | '/decidir'
    | '/historico'
    | '/login'
    | '/mapa'
    | '/meu-mapa'
    | '/perfil'
    | '/auth/callback'
    | '/auth/migrate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoPensaRoute: typeof ComoPensaRoute
  DecidirRoute: typeof DecidirRoute
  HistoricoRoute: typeof HistoricoRoute
  LoginRoute: typeof LoginRoute
  MapaRoute: typeof MapaRoute
  MeuMapaRoute: typeof MeuMapaRoute
  PerfilRoute: typeof PerfilRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthMigrateRoute: typeof AuthMigrateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-pensa': {
      id: '/como-pensa'
      path: '/como-pensa'
      fullPath: '/como-pensa'
      preLoaderRoute: typeof ComoPensaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decidir': {
      id: '/decidir'
      path: '/decidir'
      fullPath: '/decidir'
      preLoaderRoute: typeof DecidirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-mapa': {
      id: '/meu-mapa'
      path: '/meu-mapa'
      fullPath: '/meu-mapa'
      preLoaderRoute: typeof MeuMapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/migrate': {
      id: '/auth/migrate'
      path: '/auth/migrate'
      fullPath: '/auth/migrate'
      preLoaderRoute: typeof AuthMigrateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoPensaRoute: ComoPensaRoute,
  DecidirRoute: DecidirRoute,
  HistoricoRoute: HistoricoRoute,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  MeuMapaRoute: MeuMapaRoute,
  PerfilRoute: PerfilRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthMigrateRoute: AuthMigrateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
